"""Shared pytest fixtures.

Integration tests require a real `logoscore` binary and a modules directory.
They are skipped when the required env vars are not set:

    LOGOSCORE_BIN             — absolute path to the logoscore binary
    LOGOSCORE_TEST_MODULES_DIR — directory with built test module plugins

The Nix flake's `integration` check sets both. Running `pytest tests/unit`
needs neither.
"""
from __future__ import annotations

import os
import shutil

import pytest


def pytest_addoption(parser: pytest.Parser) -> None:
    parser.addoption(
        "--transport",
        action="store",
        default="local",
        help=(
            "Transport to exercise in integration tests. `local` uses "
            "QLocalSocket (default). `tcp` / `tcp_ssl` re-run the same "
            "suites against a network transport."
        ),
    )
    parser.addoption(
        "--docker-flavor",
        action="store",
        default="dev",
        help=(
            "Which logoscore:smoke-<flavor> docker image the docker "
            "smoke tests target: `dev` (default, nix-store-linked "
            "binary) or `portable` (self-contained cli-bundle-dir). "
            "Use `both` to replay the matrix against each in turn — "
            "the preferred setting in CI."
        ),
    )


@pytest.fixture(scope="session")
def logoscore_bin() -> str:
    binary = os.environ.get("LOGOSCORE_BIN") or shutil.which("logoscore")
    if not binary:
        pytest.skip("LOGOSCORE_BIN not set and `logoscore` not on PATH")
    return binary


@pytest.fixture(scope="session")
def test_modules_dir() -> str:
    path = os.environ.get("LOGOSCORE_TEST_MODULES_DIR")
    if not path:
        pytest.skip("LOGOSCORE_TEST_MODULES_DIR not set")
    return path


@pytest.fixture(scope="session")
def transport(request: pytest.FixtureRequest) -> str:
    t = request.config.getoption("--transport")
    if t not in ("local", "tcp", "tcp_ssl"):
        pytest.skip(f"unsupported --transport value: {t}")
    if t == "tcp_ssl":
        # SSL needs cert/key paths; for CI these would be generated by a
        # fixture. Not yet implemented — skip until we add one.
        pytest.skip("tcp_ssl fixture (cert/key generation) not implemented yet")
    return t


def _pick_free_port() -> int:
    """Pick an ephemeral port by binding + closing. Race-prone in theory,
    fine in practice at our test concurrency levels."""
    import socket
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


@pytest.fixture
def tcp_port() -> int:
    """Ephemeral port for the daemon's TCP listener. Tests that use the
    `tcp` transport should bind to this explicitly because the current
    daemon writes its configured --tcp-port into daemon.json verbatim
    rather than the OS-assigned one when --tcp-port=0."""
    return _pick_free_port()
