"""Integration tests calling every method on `test_basic_module_cpp`.

Mirror of `test_basic_module_methods.py` but for the pure-C++ universal
module — the impl signatures use `std::string`, `int64_t`, `uint64_t`,
`double`, `std::vector<std::string>`, `std::vector<uint8_t>`, `LogosMap`
(nlohmann::json), `LogosList`, and `StdLogosResult`. The Qt glue is
auto-generated by `logos-cpp-generator --from-header`, and this file
proves the generated glue + over-the-wire serialisation works end-to-end
for every type the generator supports.

Return-value shapes are kept identical to `test_basic_module` wherever
the mapping is lossless:

  std::string              ↔ QString                    (same shape)
  int64_t / uint64_t       ↔ int                        (same shape)
  bool                     ↔ bool                       (same shape)
  double                   ↔ double                     (same shape)
  std::vector<std::string> ↔ QStringList                (JSON array of strings)
  std::vector<uint8_t>     ↔ QByteArray                 (→ base64 or bytes; tested via size)
  LogosMap                 ↔ QVariantMap (jsonReturn)   (JSON object)
  LogosList                ↔ QVariantList (jsonReturn)  (JSON array)
  StdLogosResult           ↔ LogosResult                ({success, value, error})

See:
  repos/logos-test-modules/test-basic-module-cpp/src/test_basic_module_cpp_impl.h
  repos/logos-test-modules/test-basic-module-cpp/src/test_basic_module_cpp_impl.cpp

Skipped unless LOGOSCORE_BIN and LOGOSCORE_TEST_MODULES_DIR are set — the
Nix `integration` check wires both up (and bundles this module into the
test modules dir alongside `test_basic_module`).
"""
from __future__ import annotations

import threading
import time

import pytest

from logoscore import LogoscoreDaemon

MODULE = "test_basic_module_cpp"


@pytest.fixture(scope="module")
def client(logoscore_bin, test_modules_dir, transport, request):
    """Build a daemon + client wired to whatever transport the suite is
    parametrised on. Mirror of `test_basic_module_methods.py::client`
    — kept duplicated rather than moved to a conftest helper so each
    test file can be read end-to-end without jumping between files."""
    import socket

    def _pick_free_port() -> int:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.bind(("127.0.0.1", 0))
            return s.getsockname()[1]

    kwargs = {}
    client_kwargs: dict = {"transport": transport}
    if transport != "local":
        kwargs["transports"] = [transport]
        if transport == "tcp":
            kwargs["tcp_port"] = _pick_free_port()
        elif transport == "tcp_ssl":
            cert, key = request.getfixturevalue("self_signed_cert")
            kwargs["tcp_ssl_port"] = _pick_free_port()
            kwargs["ssl_cert"] = cert
            kwargs["ssl_key"] = key
            # Self-signed cert won't validate against any CA — the
            # client has to opt out of peer verification or every call
            # fails the TLS handshake.
            client_kwargs["no_verify_peer"] = True
    with LogoscoreDaemon(
        modules_dir=test_modules_dir, binary=logoscore_bin, **kwargs,
    ) as daemon:
        c = daemon.client(**client_kwargs)
        c.load_module(MODULE)
        yield c


# ── Return type: void ────────────────────────────────────────────────────────
# The CLI reports `true` for void returns as the success sentinel (same
# behaviour as test_basic_module). If the pure-C++ path ever diverges here
# it's a glue bug — the generated dispatch should be returning
# `QVariant(true)` for void methods on both paths.

def test_do_nothing(client):
    assert client.call(MODULE, "doNothing") is True


def test_do_nothing_with_args(client):
    assert client.call(MODULE, "doNothingWithArgs", "hello", 7) is True


# ── Return type: bool ────────────────────────────────────────────────────────

def test_return_true(client):
    assert client.call(MODULE, "returnTrue") is True


def test_return_false(client):
    assert client.call(MODULE, "returnFalse") is False


@pytest.mark.parametrize("n,expected", [(5, True), (-3, False), (0, False)])
def test_is_positive(client, n, expected):
    assert client.call(MODULE, "isPositive", n) is expected


# ── Return type: int64_t / uint64_t ──────────────────────────────────────────

def test_return_int(client):
    assert client.call(MODULE, "returnInt") == 42


def test_add_ints(client):
    assert client.call(MODULE, "addInts", 2, 3) == 5


def test_string_length(client):
    assert client.call(MODULE, "stringLength", "abcdef") == 6


def test_return_uint(client):
    assert client.call(MODULE, "returnUint") == 99


def test_echo_uint(client):
    assert client.call(MODULE, "echoUint", 123) == 123


# ── Return type: double ──────────────────────────────────────────────────────

def test_return_double(client):
    assert client.call(MODULE, "returnDouble") == pytest.approx(3.5)


def test_add_doubles(client):
    assert client.call(MODULE, "addDoubles", 1.25, 2.75) == pytest.approx(4.0)


# ── Return type: std::string ─────────────────────────────────────────────────

def test_return_string(client):
    assert client.call(MODULE, "returnString") == "test_basic_module_cpp"


def test_echo(client):
    assert client.call(MODULE, "echo", "round-trip") == "round-trip"


def test_concat(client):
    assert client.call(MODULE, "concat", "foo", "bar") == "foobar"


# ── Return type: StdLogosResult ──────────────────────────────────────────────
# Serialised the same shape as LogosResult (Qt) on the wire:
#   {"success": bool, "value": <any>, "error": <any>}
# Generator emits a StdLogosResult → Qt LogosResult conversion in the glue.
#
# Quirk: on success the impl sets `error=""`, but the glue → QVariant
# conversion treats an empty std::string as a default-constructed QVariant,
# which serialises as JSON `null` rather than an empty string. Same goes
# for `value` on failure (default-constructed nlohmann::json → QVariant()
# → null). So absent-side fields are `None` regardless of their C++ type.

def test_success_result(client):
    assert client.call(MODULE, "successResult") == {
        "success": True, "value": "operation succeeded", "error": None,
    }


def test_error_result(client):
    assert client.call(MODULE, "errorResult") == {
        "success": False, "value": None, "error": "deliberate error for testing",
    }


def test_result_with_map(client):
    assert client.call(MODULE, "resultWithMap") == {
        "success": True,
        "value": {"name": "test", "count": 42, "active": True},
        "error": None,
    }


def test_result_with_list(client):
    assert client.call(MODULE, "resultWithList") == {
        "success": True,
        "value": [{"id": 1, "label": "first"}, {"id": 2, "label": "second"}],
        "error": None,
    }


def test_validate_input_success(client):
    assert client.call(MODULE, "validateInput", "hello") == {
        "success": True,
        "value": {"input": "hello", "length": 5},
        "error": None,
    }


def test_validate_input_error(client):
    assert client.call(MODULE, "validateInput", "") == {
        "success": False, "value": None, "error": "input cannot be empty",
    }


# ── Return type: LogosMap (nlohmann::json object) ───────────────────────────
# Generator marks these `jsonReturn=true` and emits an nlohmannToQVariant
# conversion in the glue, which lands as a regular JSON object over RPC.

def test_return_map(client):
    assert client.call(MODULE, "returnMap") == {"key": "value", "number": 7}


def test_make_map(client):
    assert client.call(MODULE, "makeMap", "hello", "world") == {"hello": "world"}


# ── Return type: LogosList (nlohmann::json array) ───────────────────────────

def test_return_list(client):
    assert client.call(MODULE, "returnList") == [1, 2, 3]


def test_make_list(client):
    assert client.call(MODULE, "makeList", "x", "y") == ["x", "y"]


# ── Return type: std::vector<std::string> ───────────────────────────────────

def test_return_string_list(client):
    assert client.call(MODULE, "returnStringList") == ["one", "two", "three"]


def test_split_string(client):
    assert client.call(MODULE, "splitString", "a,b,c") == ["a", "b", "c"]


# ── Return type: std::vector<uint8_t> ───────────────────────────────────────
# QByteArray ↔ bytes serialisation varies by transport (base64 for JSON, raw
# for CBOR). Assert on the size so this test doesn't need to care about the
# binary-to-JSON encoding choice.

def test_return_bytes_size(client):
    returned = client.call(MODULE, "returnBytes")
    # json path: base64 string; cbor path: bytes/list. Either way, passing
    # it back into byteArraySize should confirm the round-trip.
    assert client.call(MODULE, "byteArraySize", returned) == 5


def test_byte_array_size(client):
    # CLI coerces @file-less positional strings to std::vector<uint8_t> via
    # QByteArray — same as the Qt module's byteArraySize test.
    assert client.call(MODULE, "byteArraySize", "12345") == 5


# ── Parameter types ─────────────────────────────────────────────────────────

def test_echo_int(client):
    assert client.call(MODULE, "echoInt", 123) == 123


@pytest.mark.parametrize("b", [True, False])
def test_echo_bool(client, b):
    assert client.call(MODULE, "echoBool", b) is b


def test_join_strings(client):
    # CLI can't construct a std::vector<std::string> positional literal, so
    # we skip the list-parameter case here — it's exercised indirectly by
    # splitString above (which produces a list on return, proving both ends
    # of the conversion).
    pytest.skip("no CLI syntax for vector<string> param; covered by splitString return")


# ── Argument counts 0–5 ─────────────────────────────────────────────────────
# Same format strings as test_basic_module — the impl uses std::to_string
# instead of QString::arg() but produces identical output.

def test_no_args(client):
    assert client.call(MODULE, "noArgs") == "noArgs()"


def test_one_arg(client):
    assert client.call(MODULE, "oneArg", "x") == "oneArg(x)"


def test_two_args(client):
    assert client.call(MODULE, "twoArgs", "x", 7) == "twoArgs(x, 7)"


def test_three_args(client):
    assert client.call(MODULE, "threeArgs", "x", 7, True) == "threeArgs(x, 7, true)"


def test_four_args(client):
    assert client.call(MODULE, "fourArgs", "x", 7, False, "y") == "fourArgs(x, 7, false, y)"


def test_five_args(client):
    assert client.call(MODULE, "fiveArgs", "x", 7, True, "y", 9) == "fiveArgs(x, 7, true, y, 9)"


# ── Events ──────────────────────────────────────────────────────────────────
# Pure-C++ impls emit events through a `std::function emitEvent` member
# that the generator auto-wires to `LogosProviderBase::emitEvent`. The
# generator's signature is `(name, data)` with `data` as a single string,
# so for multi-field events the impl packs the payload as JSON.

def test_emit_test_event(client):
    received: list[dict] = []
    evt = threading.Event()

    def on_event(event: dict) -> None:
        received.append(event)
        evt.set()

    with client.on_event(MODULE, "testEvent", on_event):
        time.sleep(0.5)  # let the watcher subscribe before emitting
        client.call(MODULE, "emitTestEvent", "hello-cpp")
        assert evt.wait(timeout=10.0), "testEvent not received"

    assert received, "expected at least one event"
    assert "hello-cpp" in str(received[0])


def test_emit_multi_arg_event(client):
    """Impl packs (name, count) as a JSON string payload. Assert both
    fragments round-trip."""
    received: list[dict] = []
    evt = threading.Event()

    def on_event(event: dict) -> None:
        received.append(event)
        evt.set()

    with client.on_event(MODULE, "multiArgEvent", on_event):
        time.sleep(0.5)
        client.call(MODULE, "emitMultiArgEvent", "cpp-label", 77)
        assert evt.wait(timeout=10.0), "multiArgEvent not received"

    flat = str(received[0])
    assert "cpp-label" in flat
    assert "77" in flat
