name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64-linux
            runner: ubuntu-latest
          - arch: aarch64-linux
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - uses: cachix/cachix-action@v15
        with:
          name: logos-co
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build package
        run: nix build --print-build-logs

      - name: Run unit tests
        run: nix build '.#checks.${{ matrix.arch }}.unit' --print-build-logs

      - name: Run integration tests
        run: nix build '.#checks.${{ matrix.arch }}.integration' --print-build-logs
